modLoader = "javafml"
loaderVersion = "[0,)"
license = "MIT"
issueTrackerURL = "https://github.com/MarkusBordihn/Cookies-Candy-and-Cakes/issues"

[[mods]]
modId = "cookies_candy_and_cakes"
version = "${file.jarVersion}"
displayName = "Cookies, Candy and Cakes"
displayURL = "https://curseforge.com/minecraft/mc-mods/cookies_candy_and_cakes"
logoFile = "logo.png"
credits = ""
authors = "Markus Bordihn"
description = '''Add cookies, candy and cakes for Halloween and other holidays. Fun seasonal treats with optional effects and mob drops. Fully configurable for servers and singleplayer.'''

[[dependencies.cookies_candy_and_cakes]]
modId = "forge"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cookies_candy_and_cakes]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"
